### ISSUE TITLE
Problems regarding string matching

### ISSUE THREAD

**Issue by shilik** [TonPC64/vue-highlight-text#1]
Hi, Thanks for the great plugin.
I have a great time playing with it. But I found a strange result when dealing with string-matching.
Sometimes it works like charm. but sometime it doesn't even with only a little difference between two strings. Any suggestion for this?
BTW, what is the new feature of "sensitive", I have tried to change the Boolean value of sensitive, but can't tell the difference.

Best.

Shilik

![not-ok](https://user-images.githubusercontent.com/1404868/39231719-9212df06-489d-11e8-8062-5fdafd9a08d5.png)
![working](https://user-images.githubusercontent.com/1404868/39231725-9784fa0a-489d-11e8-8ad0-0aac74f77c86.png)

**Comment by TonPC64** [comment]
Hi @shilik 
feature 'sensitive' use for search in text with case sensitive or case insensitive in English
