### ISSUE TITLE
how to use in a for loop

### ISSUE THREAD

**Issue by nikon321** [TonPC64/vue-highlight-text#2]
< ul>
        < li v-for="item in data" v-highlight="{keyword: '1'}"> {{ item.name }} < /li>
< /ul>

data : [
            {
                  name: 1
           },
          {
                  name: 2
          },
           {
                 name: 3
          }
]
result:
3
3
3

**Comment by TonPC64** [comment]
Oh!! Thank you. I will fix it now

**Comment by TonPC64** [comment]
fixed in version 1.3.2
