### ISSUE TITLE
Multiple keywords matching

### ISSUE THREAD

**Issue by shabai517** [TonPC64/vue-highlight-text#4]
Hi,
   Is that the keyword support an array? If I may have multiple keywords needed to be matched, how could I do it?

  Thanks!

**Comment by TonPC64** [comment]
Hi @shabai517 
This issue is interesting. I will try it.

**Comment by TonPC64** [comment]
@shabai517 
I added a feature to support multiple keywords in version 1.4.0.
PS.Maybe have a bug haha
